---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: maven
    tag: latest
    
inputs:
  - name: app1
  
outputs:
  - name: resource-app
  
run:
  path: app1/ci/build.sh
